### ISSUE TITLE
Play triangle size and positioning is not responsive in a good way

### ISSUE THREAD

**Issue by randy-r** [randy-r/redux-snake#11]
_Solution_: Ditch the unicode and replace it with a div. 
http://apps.eky.hk/css-triangle-generator/

```css
#triangle {
  width: 0;
  height: 0;
  border-style: solid;
  border-width: 100px 0 100px 173.21px; /* 100 * tan(pi/3) */
  border-color: transparent transparent transparent #66ff00;
}
```
